set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -sg escape-time 10

set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g history-limit 50000

unbind %
bind -r \\ split-window -h -c "#{current_path}"
unbind '"'
bind -r - split-window -v -c "#{current_path}"

unbind r
bind r source-file ~/.tmux.conf \; display "Tmux Config Reloaded!"

unbind Ctrl-Left
unbind Ctrl-Right
unbind Ctrl-Up
unbind Ctrl-Down
unbind Left
unbind Right
unbind Up
unbind Down

bind -r Left resize-pane -L 5
bind -r Down resize-pane -D 5
bind -r Up resize-pane -U 5
bind -r Right resize-pane -R 5

bind -r h previous-window
bind -r l next-window

bind -r m resize-pane -Z

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

set -g set-clipboard on
#set-option -g allow-rename off

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @birds-resurrect-strategy-nvim 'session'
set -g @plugin 'omerxx/tmux-sessionx'

set -g @plugin 'catppuccin/tmux'
# set -g @catppuccin_window_status_style "rounded"

run '~/.tmux/plugins/tpm/tpm'
